apiVersion: v1
kind: Pod
metadata:
  name: rdf-openroad
  namespace: rdf
spec:
  volumes:
  - name: rdf-workspace
    persistentVolumeClaim:
      claimName: rdf-workspace-pv-claim
  containers:
  - name: shell
    resources:
      limits:
        cpu: 2
        memory: 16Gi 
    image: "jinwookjung/rdf"
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - name: rdf-workspace
      mountPath: /workspace
