apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdf-workspace-pv-claim
  namespace: rdf
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
